version: "3.9"

services:
  flask: &flask
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: local_flask_socketio
    volumes:
      - .:/app  
    ports:
      - "3000:3000"
    command: /start