version: "3.9"

services:
  flask: &flask
    build:
      context: .
      dockerfile: ./compose/production/flask/Dockerfile
    image: production_flask_server
    volumes:
      - .:/app
    expose:
      - 3000
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: production_nginx_server
    depends_on:
      - flask
    ports:
      - 3000:3000
      - 80:80
      - 443:443

volumes:
  static_volume: